@extends('layouts.app')

@section('content')
@php
    // Resolve image URL with fallbacks
    $imgUrl = null;
    if (!empty($event->image_url_path)) {
        $candidate = $event->image_url_path;
        if (strpos($candidate, 'http://') === 0 || strpos($candidate, 'https://') === 0 || strpos($candidate, '/') === 0) {
            $url = $candidate;
        } else {
            $url = asset($candidate);
        }
        $path = parse_url($url, PHP_URL_PATH) ?: '';
        $localPath = public_path(ltrim($path, '/'));
        if ($path && file_exists($localPath)) {
            $imgUrl = $url;
        } else {
            $basename = basename($candidate);
            if (file_exists(public_path('events/'.$basename))) {
                $imgUrl = asset('events/'.$basename);
            } elseif (file_exists(public_path('storage/events/'.$basename))) {
                $imgUrl = asset('storage/events/'.$basename);
            } elseif (file_exists(storage_path('app/public/events/'.$basename))) {
                $imgUrl = asset('storage/events/'.$basename);
            }
        }
    }

    // Get facility bookings
    $facilityBookings = collect([]);
    if (\Illuminate\Support\Facades\Schema::hasTable('facility_bookings')) {
        $facilityBookings = \Illuminate\Support\Facades\DB::table('facility_bookings')
            ->where('event_id', $event->id)
            ->orderBy('start_at')
            ->get();
    }

    // Organizer display
    $organizerName = optional($event->organizer)->name ?? 'Unknown Organizer';
@endphp

<div class="w-full max-w-7xl mx-auto px-4 md:px-10 py-8">
    <!-- Back Button -->
    @php
        $society = $event->societies()->first();
    @endphp
    <a href="{{ $society ? route('society.show', $society) . '#events' : route('events.index') }}" class="inline-flex items-center text-primary hover:text-blue-700 mb-6 transition-colors">
        <span class="material-symbols-outlined mr-2">arrow_back</span>
        <span class="font-medium">{{ $society ? 'Back to ' . $society->societyName : 'Back to Events' }}</span>
    </a>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <!-- Left Column: Image & Quick Info -->
        <div class="lg:col-span-1 space-y-6">
            <!-- Event Image -->
            <div class="bg-white dark:bg-[#1a202c] rounded-xl overflow-hidden shadow-lg">
                @if($imgUrl)
                    {{-- SECURITY: Image src is safe - generated by asset() helper --}}
                    <img src="{{ $imgUrl }}" alt="@attr($event->name)" class="w-full h-64 object-cover">
                @else
                    <div class="w-full h-64 bg-gradient-to-br from-blue-100 to-blue-200 dark:from-blue-900 dark:to-blue-800 flex items-center justify-center">
                        <span class="material-symbols-outlined text-gray-400 dark:text-gray-600" style="font-size: 80px;">event</span>
                    </div>
                @endif
            </div>

            <!-- Quick Info Card -->
            <div class="bg-white dark:bg-[#1a202c] rounded-xl shadow-lg p-6 space-y-4">
                <h3 class="text-lg font-bold text-[#111318] dark:text-white border-b border-gray-200 dark:border-gray-700 pb-3">
                    Event Information
                </h3>
                
                <div class="space-y-3 text-sm">
                    <div class="flex items-center gap-3">
                        <span class="material-symbols-outlined text-primary">person</span>
                        <div>
                            <p class="text-[#616f89] dark:text-gray-400">Organizer</p>
                            {{-- SECURITY: HTML context - auto-encoded with {{ }} --}}
                            <p class="font-semibold text-[#111318] dark:text-white">{{ $organizerName }}</p>
                        </div>
                    </div>

                    <div class="flex items-center gap-3">
                        <span class="material-symbols-outlined text-primary">flag</span>
                        <div>
                            <p class="text-[#616f89] dark:text-gray-400">Status</p>
                            <span class="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold
                                @if($event->status === 'open') bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200
                                @elseif($event->status === 'incoming') bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200
                                @elseif($event->status === 'closed') bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200
                                @elseif($event->status === 'cancelled') bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200
                                @else bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200
                                @endif">
                                {{-- SECURITY: HTML context - auto-encoded --}}
                                {{ strtoupper($event->status ?? 'TBD') }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Right Column: Details -->
        <div class="lg:col-span-2 space-y-6">
            <!-- Event Title & Status -->
            <div class="bg-white dark:bg-[#1a202c] rounded-xl shadow-lg p-8">
                {{-- SECURITY: HTML context - auto-encoded --}}
                <h1 class="text-4xl font-bold text-[#111318] dark:text-white mb-4">{{ $event->name }}</h1>
                
                <!-- Date & Location -->
                <div class="flex flex-wrap gap-6 text-[#616f89] dark:text-gray-400 mb-6">
                    @if($event->start_date)
                        <div class="flex items-center gap-2">
                            <span class="material-symbols-outlined text-primary">calendar_month</span>
                            {{-- SECURITY: Date is safe - formatted by Carbon --}}
                            <span class="font-medium">{{ \Carbon\Carbon::parse($event->start_date)->format('M d, Y • h:i A') }}</span>
                        </div>
                    @endif
                    @if($event->location)
                        <div class="flex items-center gap-2">
                            <span class="material-symbols-outlined text-primary">place</span>
                            {{-- SECURITY: HTML context - auto-encoded --}}
                            <span class="font-medium">{{ $event->location }}</span>
                        </div>
                    @endif
                </div>
            </div>

            <!-- Description -->
            <div class="bg-white dark:bg-[#1a202c] rounded-xl shadow-lg p-8">
                <h2 class="text-2xl font-bold text-[#111318] dark:text-white mb-4 flex items-center gap-2">
                    <span class="material-symbols-outlined text-primary">description</span>
                    About This Event
                </h2>
                {{-- SECURITY: HTML context - auto-encoded, whitespace preserved --}}
                <p class="text-[#616f89] dark:text-gray-300 leading-relaxed whitespace-pre-line">
                    {{ $event->description ?? 'No description provided for this event.' }}
                </p>
            </div>

            <!-- Event Details -->
            <div class="bg-white dark:bg-[#1a202c] rounded-xl shadow-lg p-8">
                <h2 class="text-2xl font-bold text-[#111318] dark:text-white mb-6 flex items-center gap-2">
                    <span class="material-symbols-outlined text-primary">info</span>
                    Event Details
                </h2>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div class="flex items-start gap-3">
                        <span class="material-symbols-outlined text-primary mt-1">schedule</span>
                        <div>
                            <p class="font-semibold text-[#111318] dark:text-white">Start Date</p>
                            {{-- SECURITY: Date is safe - formatted by Carbon --}}
                            <p class="text-[#616f89] dark:text-gray-400">{{ $event->start_date ? \Carbon\Carbon::parse($event->start_date)->format('F d, Y • h:i A') : 'TBD' }}</p>
                        </div>
                    </div>

                    <div class="flex items-start gap-3">
                        <span class="material-symbols-outlined text-primary mt-1">event</span>
                        <div>
                            <p class="font-semibold text-[#111318] dark:text-white">End Date</p>
                            {{-- SECURITY: Date is safe - formatted by Carbon --}}
                            <p class="text-[#616f89] dark:text-gray-400">{{ $event->end_date ? \Carbon\Carbon::parse($event->end_date)->format('F d, Y • h:i A') : 'TBD' }}</p>
                        </div>
                    </div>

                    <div class="flex items-start gap-3">
                        <span class="material-symbols-outlined text-primary mt-1">location_on</span>
                        <div>
                            <p class="font-semibold text-[#111318] dark:text-white">Location</p>
                            {{-- SECURITY: HTML context - auto-encoded --}}
                            <p class="text-[#616f89] dark:text-gray-400">{{ $event->location ?? 'TBD' }}</p>
                        </div>
                    </div>

                    <div class="flex items-start gap-3">
                        <span class="material-symbols-outlined text-primary mt-1">people</span>
                        <div>
                            <p class="font-semibold text-[#111318] dark:text-white">Capacity</p>
                            {{-- SECURITY: Numeric value - safe --}}
                            <p class="text-[#616f89] dark:text-gray-400">{{ $event->capacity ?? 'Unlimited' }}</p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Available Tickets (if ticketed event) -->
                <div class="bg-white dark:bg-[#1a202c] rounded-xl shadow-lg p-8" id="tickets">
                    <h2 class="text-2xl font-bold text-[#111318] dark:text-white mb-6 flex items-center gap-2">
                        Available Tickets
                    </h2>
                    <div class="space-y-4">
                        @foreach($tickets as $ticket)
                            @php
                                $available = $ticket->total_quantity - $ticket->sold_quantity;
                                $isFree = $ticket->price == 0;
                            @endphp
                            <div class="border-2 border-gray-200 dark:border-gray-700 rounded-lg p-5 hover:border-primary transition-colors">
                                <div class="flex justify-between items-start">
                                    <div class="flex-1">
                                        {{-- SECURITY: HTML context - auto-encoded --}}
                                        <h3 class="text-lg font-bold text-[#111318] dark:text-white mb-2">{{ $ticket->ticket_name }}</h3>
                                        <div class="flex items-center gap-4 text-sm text-[#616f89] dark:text-gray-400">
                                            {{-- SECURITY: Numeric values - safe --}}
                                            <span class="{{ $available > 0 ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400' }} font-semibold">
                                                {{ $available }} / {{ $ticket->total_quantity }} Available
                                            </span>
                                            @if($ticket->sales_start_at || $ticket->sales_end_at)
                                                <span>
                                                    @if($ticket->sales_start_at)
                                                        From {{ \Carbon\Carbon::parse($ticket->sales_start_at)->format('M d') }}
                                                    @endif
                                                    @if($ticket->sales_end_at)
                                                        - {{ \Carbon\Carbon::parse($ticket->sales_end_at)->format('M d') }}
                                                    @endif
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="text-right">
                                        {{-- SECURITY: Numeric values - safe, number_format used --}}
                                        <p class="text-3xl font-bold {{ $isFree ? 'text-green-600 dark:text-green-400' : 'text-primary' }}">
                                            {{ $isFree ? 'FREE' : 'RM ' . number_format($ticket->price, 2) }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                    
                    @auth
                        @if(!$hasJoined)
                            <div class="mt-6">
                                {{-- SECURITY: Route helper generates safe URLs --}}
                                <a href="{{ route('events.tickets.purchase', $event) }}" class="block w-full bg-primary hover:bg-blue-700 text-white font-bold py-4 rounded-lg transition-colors text-center">
                                    Select & Purchase Tickets
                                </a>
                            </div>
                        @endif
                    @else
                        <div class="mt-6">
                            <a href="{{ route('login') }}" class="block w-full bg-primary hover:bg-blue-700 text-white font-bold py-4 rounded-lg transition-colors text-center">
                                Login to Purchase Tickets
                            </a>
                        </div>
                    @endauth
                </div>

            <!-- Facility Bookings -->
            @if($facilityBookings->count())
                <div class="bg-white dark:bg-[#1a202c] rounded-xl shadow-lg p-8">
                    <h2 class="text-2xl font-bold text-[#111318] dark:text-white mb-6 flex items-center gap-2">
                        <span class="material-symbols-outlined text-primary">meeting_room</span>
                        Facility Bookings
                    </h2>
                    <div class="space-y-3">
                        @foreach($facilityBookings as $booking)
                            <div class="border border-gray-200 dark:border-gray-700 rounded-lg p-4">
                                <div class="flex justify-between items-center">
                                    <div>
                                        {{-- SECURITY: Numeric ID - safe --}}
                                        <p class="font-semibold text-[#111318] dark:text-white">Booking #{{ $booking->id }}</p>
                                        {{-- SECURITY: Dates from database - safe --}}
                                        <p class="text-sm text-[#616f89] dark:text-gray-400">
                                            {{ $booking->start_at }} → {{ $booking->end_at }}
                                        </p>
                                    </div>
                                    <span class="px-3 py-1 rounded-full text-xs font-semibold
                                        @if($booking->status === 'approved') bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200
                                        @elseif($booking->status === 'pending') bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200
                                        @else bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200
                                        @endif">
                                        {{-- SECURITY: HTML context - auto-encoded --}}
                                        {{ ucfirst($booking->status) }}
                                    </span>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>
@endsection

{{--
SECURITY NOTES:
================
✅ All user input (event name, description, location) is auto-encoded with {{ }}
✅ Image src uses asset() helper which is safe
✅ Dates are formatted by Carbon - safe
✅ Numeric values (capacity, prices, quantities) are safe
✅ Route helpers generate safe URLs
✅ No JavaScript injection points
✅ No inline event handlers
✅ No user-generated CSS
--}}